version: '3.8'

services:
  web:
    build: .
    container_name: flask_app
    restart: unless-stopped
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    environment:
      - FLASK_ENV=development
      - SECRET_KEY=john1
    command: flask run --host=0.0.0.0
