name: ZAP DAST Security Scan

on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: read
  actions: write
  security-events: write

jobs:
  zap_scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker
        run: |
          sudo apt-get update
          sudo apt-get install -y curl
          curl -fsSL https://get.docker.com | sh
          sudo usermod -aG docker $USER
          sudo systemctl enable docker
          sudo systemctl start docker
          sudo curl -L "https://github.com/docker/compose/releases/download/v2.23.0/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose

      - name: Pull OWASP ZAP image
        run: docker pull owasp/zap2docker-stable:latest

      - name: Start application
        run: |
          docker-compose up -d --build
          echo "Waiting for application to be ready..."
          timeout 120 bash -c 'while [[ "$(curl -s -o /dev/null -w ''%{http_code}'' http://localhost:5000)" != "200" ]]; do 
            sleep 5; 
            echo "Retrying connection to application...";
            docker-compose logs --tail=20;
          done' || false

      - name: Run ZAP Baseline Scan
        run: |
          docker run --rm \
          -v $(pwd):/zap/wrk \
          -t owasp/zap2docker-stable:latest \
          zap-baseline.py \
          -t http://host.docker.internal:5000 \
          -g gen.conf \
          -r zap-report.html \
          -x zap-report.xml \
          -a \
          -d

      - name: Upload ZAP Scan Reports
        uses: actions/upload-artifact@v3
        with:
          name: zap-security-reports
          path: |
            zap-report.html
            zap-report.xml
          retention-days: 5

      - name: Cleanup
        if: always()
        run: |
          docker-compose down
          docker system prune -f