name: ZAP DAST

on:
  push:
    branches:
      - main

jobs:
  zap_scan:
    runs-on: ubuntu-latest
    services:
      web:
        image: python:3.129
        ports:
          - 5000:5000
        options: >-
          --health-cmd="curl --fail http://localhost:5000 || exit 1"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5
        volumes:
          - .:/app
        env:
          FLASK_APP: run.py
        command: >
          bash -c "pip install -r /app/requirements.txt &&
                   python /app/run.py"

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Wait for web service
        run: |
          sleep 20
          curl -I http://localhost:5000

      - name: Run ZAP Baseline Scan
        uses: zaproxy/action-baseline@v0.10.0
        with:
          target: 'http://localhost:5000'
          fail_action: false
          artifact_name: 'zap-report'
          docker_name: 'owasp/zap2docker-stable'
