name: ZAP DAST Security Scan

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  zap_scan:
    runs-on: ubuntu-latest
    container:
      image: owasp/zap2docker-stable

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Start application
        run: |
          docker-compose up -d --build
          echo "Waiting for application to be ready..."
          timeout 60 bash -c 'while [[ "$(curl -s -o /dev/null -w ''%{http_code}'' http://localhost:5000)" != "200" ]]; do 
            sleep 5; 
          done' || false

      - name: Run ZAP Baseline Scan
        run: |
          zap-baseline.py -t http://host.docker.internal:5000 \
          -c zap-baseline.conf \
          -r report.html \
          -x report.xml \
          --hook=zap_hooks.py \
          -a

      - name: Store reports
        uses: actions/upload-artifact@v3
        with:
          name: zap-security-reports
          path: |
            report.html
            report.xml

      - name: Cleanup
        if: always()
        run: docker-compose down